### ISSUE TITLE
Move Widgets to individual libraries

### ISSUE THREAD

**Issue by jposada202020** [adafruit/Adafruit_CircuitPython_DisplayIO_Layout#32]
# Context

Updated 2021-04-08: Please come back for news and developments regarding this

~~After the discussion in the CircuitPython meeting on 2021-04-05, it was discussed that individual widgets will be moved to individual libraries. This will help users find the widgets more easily. The DisplayIO library will keep the layouts configuration and the general helpers.~~

## Modifications
This change will have two types of consequences, in the widget itself, and in the library.

### Widget level:
* Examples change [Imports]
* Change in the widget source file in case using methods stored in __init__.py

### Library level:
* Change in the API.rst file [modules]
* Change in conf.py [ autodoc]
* Change in examples.rst [examples will be moved to a different location]
* Change in __init__.py

## Libraries to be moved will be
- Annotation
- Cartesian
- Dial
- Flip-input
- Icon-animated
- Icon_widget
- Switch-Round

work will start with widgets not in PR as they are easier to move. After that alphabetical order will be used. 
@kmatch98 @FoamyGuy if for any reason you don't want your widget to be moved let me know, or if you want to move the module yourself, please let me know also. 

This wil probably raise a new library version as folks would need to rewrite their scripts

**Comment by kmatch98** [comment]
I think icon_widget and icon_animated should live together as a family. @FoamyGuy your thoughts?

The others are fine to move into separate libraries.  I appreciate if you can move them to their new home. 

Any suggestions on how best to make all the widgets “discoverable” as a group?  How do we ensure folks can easily find all the cool widgets?   (Even I am having trouble keeping all these neat new things in my mind!)

**Comment by jposada202020** [comment]
@kmatch98 A new cool and beautiful learning guide from @FoamyGuy :)

**Comment by jposada202020** [comment]
@kmatch98 No problem will do, Scott mentioned the possibility the have different variants of the same thing in a library, so _icon and icon_widget as you mentioned could be in just one Icon library if you agree.

**Comment by FoamyGuy** [comment]
Agreed icon_widget and icon_animated can go together. 

There is a list in the main displayio learn guide here: https://learn.adafruit.com/circuitpython-display-support-using-displayio/helper-libraries

We could add to that as we get the new libraries created.

**Comment by jposada202020** [comment]
First one is in 
Color Picker
https://github.com/jposada202020/Adafruit_CircuitPython_DisplayIO_Color_Picker/runs/2274359264

However I am having problems when importing the parent classes when building the docs, I have tested in the board and it works. I have tested both ways of calls, standard

```python
        Widget.__init__(
            self, x=x, y=y, height=image_size, width=image_size, **kwargs, max_size=4
        )
        Control.__init__(self)
```

and the way kmatch uses in the other widgets without a a good results in building the docs, the message is

``    class ColorPicker(Widget, Control):
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases``
If you folks know a good way to deal with this, help will be appreciate, I will put a ote in discord.

**Comment by jposada202020** [comment]
Ongoing changes. Closing here
