### ISSUE TITLE
Needs to be added to bundle.

### ISSUE THREAD

**Issue by kattni** [adafruit/Adafruit_CircuitPython_DisplayIO_Layout#8]
@kmatch98 [This guide page](https://learn.adafruit.com/creating-and-sharing-a-circuitpython-library/sharing-in-the-community-bundle) covers the process if you'd like to add it to the Adafruit CircuitPython Bundle.

**Comment by FoamyGuy** [comment]
[#289](https://github.com/adafruit/Adafruit_CircuitPython_Bundle/pull/298) has been created for this.
